Default: &defaults
  user: yesodoverflow
  password: yesodoverflow
  host: localhost
  port: 5432
  database: yesodoverflow
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: yesodoverflow_test
  <<: *defaults

Staging:
  database: yesodoverflow_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesodoverflow_production
  poolsize: 100
  <<: *defaults
