#!/bin/bash
cd
echo "Installing yesod."
cabal update
cabal install cabal-install
cabal install cabal-dev
export PATH=$HOME/.cabal/bin:$PATH
cd yesodoverflow/yesodoverflow
cabal-dev install
cabal-dev clean
cabal-dev configure
cabal-dev build
cd ..
echo "Installing dotCloud scaffolding."
cat >run <<EOF
#!/bin/bash
cd \$HOME/yesodoverflow/yesodoverflow/
exec ./dist/build/yesodoverflow/yesodoverflow Production --port \$PORT_WWW
EOF
    chmod +x run
cat >profile <<EOF
export PATH=\$HOME/.cabal/bin:\$PATH
EOF
